on: 
 push
name: Jira Issue creation with Build summary
jobs:
  jiraIssueBuild:
    name: Jira Issue Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Login
      uses: atlassian/gajira-login@master
      env:
       JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
       JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
       JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Create
      id: Create
      uses: atlassian/gajira-create@master
      with:
       project: GJD
       issuetype: Task
       summary: |
        Build completed for ${{ github.repository }}
       description: Updation and creation of JIRA issues
       
    - name: Log created issue
      run: echo "Issue ${{ steps.create.output.issue }} was created"